spring:
  application:
    name: replication-core-rabbitmq

  rabbitmq:
    host: localhost
    port: 5672
    username: abayu_management
    password: abayu_management
    virtual-host: replication_core_rabbit

replication-rabbit:
  queue: replication_core_rabbit
  exchange: product.updated.data
  routing-key: product.updated.data

server:
  port: 8082
